### ISSUE TITLE
One page not pulling in banner include

### ISSUE THREAD

**Issue by Trott** [ucsf-ckm/ucsf-history-website#12]
Any reason `buildings-05202008.html` isn't pulling in `ucsf_banner.html` while everything else does?

**Comment by Trott** [comment]
It's also apparently not using the `footer.html` include either.

**Comment by stopfstedt** [comment]
checked the history of this file, it always deviated like this from the rest of the page-files. so this is nothing that was introduced during the PHP to LT conversion.

content-wise, it is identical with `buildings.html`.

finally, it is also not being linked to from anywhere within the page.

gunk, will be removed.

**Comment by stopfstedt** [comment]
resolved by removing obsolete file. deployed to gh.io
